name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: get working directory
        run: echo $PWD && cd example
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_lualatex: true
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: cv.pdf